SmartDog/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('smartdog/',include('gadgets.urls')),
]

gadgets/urls.py
from django.urls import path
from gadgets import views
from SmartDog import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login,logout

urlpatterns = [
    path('',views.home,name='home'),
    path('cart/',views.cart,name='cart'),
    path('experts/',views.expert,name='expert'),
    path('login/',login,{'template_name':'gadgets/login.html'},name='login'),
    path('dog_training/',views.dogtrain,name='dogtrain'),
    path('dog_grooming/',views.doggroom,name='doggroom'),
    path('dog_selfwash/',views.dogwash,name='dogwash'),
    path('dog_sitting/',views.dogsit,name='dogsit'),
    path('veterinary_care/',views.vetercare,name='vetercare'),
    path('pet_adoptions/',views.petadopt,name='petadopt'),
    path('<slug:menu>',views.summary,name='summary'),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

gadgets/models.py
from django.db import models

class Catlog(models.Model):
    title = models.CharField(max_length=100)
    category = models.SlugField(max_length=200,unique=True)

    def __str__(self):
        return "title: " + self.title + " Catlog: " + self.category

class Product(models.Model):
    cat_id=models.ForeignKey(Catlog,on_delete=models.CASCADE)
    ptitle=models.CharField(max_length=100)
    discrip=models.TextField(max_length=1000)
    price=models.DecimalField(default=0,max_digits=12,decimal_places=4)
    act_price=models.DecimalField(default=0,max_digits=12,decimal_places=4)
    color=models.CharField(max_length=50,null=True)
    size=models.CharField(max_length=50,null=True)
    image=models.FileField(upload_to="static/images")
    brand=models.CharField(max_length=100,null=True)
    rating=models.DecimalField(decimal_places=1,max_digits=2,default=0,null=True)
    review=models.TextField(max_length=400,null=True)


    def __str__(self):
        return "Product: "+self.ptitle +" Brand: "+self.brand

gadgets/views.py
from django.shortcuts import render
from .models import Catlog,Product
# Create your views here.
def home(request):
    a=Catlog.objects.all()
    s=set([i.title for i in a])
    d={}
    for i in s:
        x = Catlog.objects.filter(title=i)
        sub = [j.category for j in x]
        d[i] = sub

    return render(request,"gadgets/home.html",{"menus":d})

def summary(request,menu):
    a=Catlog.objects.get(category=menu)
    return render(request,"gadgets/summary.html",{"cat":a})

def cart(request):
    return render(request,"gadgets/cart.html")


def expert(request):
    return render(request,"gadgets/experts.html")

def dogtrain(request):
    return render(request,"gadgets/dog_training.html")

def dogwash(request):
    return render(request,"gadgets/dog_selfwash.html")

def doggroom(request):
    return render(request,"gadgets/dog_grooming.html")

def dogsit(request):
    return render(request,"gadgets/dog_sitting.html")

def petadopt(request):
    return render(request,"gadgets/pet_adoptions.html")

def vetercare(request):
    return render(request,"gadgets/veterinary_care.html")

gadgets/templates/gadgets/base.html
<!DOCTYPE html>
<html lang="en">
<head>
{% load staticfiles %}
    <meta charset="UTF-8">

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
   <title>{% block title %} {% endblock %}</title>
<link type="text/css" rel="stylesheet" href="{% static 'css/footer.css' %}">
</head>
<body>


<nav class="navbar " style="background-color: orange">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><img src="{% static 'images/dog_logo1.jpg' %}" height="106" width="127" style="position: relative;left: -16px;top: -16px"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'home' %}" style="color: white">Home <span class="sr-only">(current)</span></a></li>

      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search by Dog ...">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'expert' %}"><span class="glyphicon glyphicon-envelope" style="color: white">Experts</span></a></li>
        <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-user" style="color: white">Login</span></a></li>
        <li><a href="{% url 'cart' %}"><span class="glyphicon glyphicon-shopping-cart" style="color: white">Cart</span></a></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  {% block menu %}{% endblock %}
  </div><!-- /.container-fluid -->
</nav>

</body>{% block body %}{% endblock %}


 <div class="containr">
  <img src="{% static 'images/footer.jpg' %}" alt="Notebook" style="width:100%;">
  <div class="content">
    <h2>CompanyAddress</h2>

    <p>165 section B Bichhiya</p>
    <p>ABC road Near P.A.C.</p>
    <p>U.P. - 273001</p>
    <p>India</p><hr>
      <div style="text-align: center">
            Terms & Conditions. Privacy Policy. Site map
            <br>@2018 SmartDog Product Supplies, Inc. All rights reserved.

        </div>
  </div>

    <div class="conten">
    <h2 style="padding-left: 30px">Services</h2>

    <p><a href="{% url 'dogtrain' %}"><span style="color: white;">Dog Training</span></a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'doggroom' %}"><span style="color: white">Dog Grooming</span></a></p>
    <p><a href="{% url 'dogwash' %}"> <span style="color: white;"> Dog Self Wash</span></a> &nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'vetercare' %}"> <span style="color: white"> Veterinary care</span></a></p>
        <p><a href="{% url 'dogsit' %}"><span style="color: white;">Dog Sitting </span></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="{% url 'petadopt' %}"><span style="color: white">Dog Adoptions</span></a></p>
  </div>

    <div class="conte">
    <h2>CompanyAddress</h2>

    <p>165 section B Bichhiya</p>
    <p>ABC road Near P.A.C.</p>
    <p>U.P. - 273001</p>
    <p>India</p>


  </div>

</div>

</html>

gadgets/templates/gadgets/cart.html
{% extends 'gadgets/base.html' %}
{% block title %}Your Bag{% endblock %}
{% block body %}
    <h2 style="text-align: center">Your Bag is Empty!</h2>
{% endblock %}

gadgets/templates/gadgets/dog_grooming.html
{% extends 'gadgets/base.html' %}
{% block title %}Dog Grooming{% endblock %}
{% block body %}
    <h1 style="text-align: center">Dog Grooming Tips</h1>
    <h3>1. BRUSH THEIR COATS TO KEEP THEIR FUR AND SKIN HEALTHY AND CLEAN</h3>
    <p>Brushing your dog will remove dirt, debris, dead hair and unpleasant odors from the coat and the skin. It distributes the natural oils, making your dog’s coat shiny and healthy. Proper brushing will eliminate matting and tangling, which will make your next grooming appointment go more smoothly (and your Groomer very happy!).

Your longer-haired pooch needs more than just a brushing to keep his coat matt free. Follow-up the brushing by using a metal comb to get down to the skin and locate any matts that may be starting to form. Proceed gently with a metal comb, especially if your pup’s skin is particularly sensitive.</p>
<br>
    <h3>2. BRUSH THEIR TEETH ATLEAST ONCE A DAY</h3>
    <p>We have guests who only get their teeth brushed when they visit our salon, but that’s not nearly enough. Ideally, you should brush your dog’s teeth daily, but even 2 – 3 times a week makes a big difference. Use only toothpaste made especially for dogs. Dogs can’t spit, and human toothpaste contains unsafe ingredients which could make him sick if he were to swallow it. I use a child’s toothbrush so it’s softer on my dog’s gums, but a lot of people have good luck with the rubber finger brush. If you still find it difficult to brush your dog’s teeth, dental sprays and specially designed chew treats can be helpful.</p>
<br>
    <h3>3. TRIM THEIR NAILS</h3>
    <p>Just like humans, some dog’s nails grow more quickly than others. Some may require trimming every 2 weeks, and some can wait a full 6 weeks. Nail trimming is everyone’s least favorite task. Since you are diligent about your 6 – 8 week grooming visits, you can most-likely get by with just “tipping” the end of the nail to avoiding the doggie drama that often accompanies at-home nail trims. If the tap, tap, tap of nails on your hardwood floors is driving you crazy, you can always stop by and we will be happy to trim your dog’s nails for you while you wait.</p>
<br>
    <h3>4. CLEAN THEIR EARS TO PREVENT INFECTION</h3>
    <p>All dogs need their ears cleaned at least monthly. But if you have a dog with longer or heavier ears that flop over the ear canal, more frequent ear cleaning is a must. A buildup of bacteria or wax in the ears can lead to infection. If you don’t have doggie ear cleaner at home, there are plenty of ear cleaner “recipes” online… with ingredients generally on-hand like vinegar, hydrogen peroxide, etc.. Wet a cotton ball with your cleansing solution and clean the outside area first, gradually working your way towards the inner area. It is not recommended to use cotton swabs deep inside the ear canal, but you can use them to gently clean inside the ear folds on the outer ear flaps. If your dog is a frequent swimmer, it is advisable to clean and dry their ears each time after swimming.</p>
<br>
    <h3>5. WASH THEIR FACE TO ELIMINATE BACTERIA</h3>
    <p>Some breeds like bulldogs and shar peis have wrinkles or skin folds on their face. Moisture can accumulate within those folds to set-up the perfect environment for yucky bacteria. Bacteria can then lead to dermatitis or worse, infection. It is important to keep these folds clean and dry. A warm washcloth or even baby wipes will do the trick. If redness, bumps or odor becomes a problem, see your vet. A more stringent cleaning schedule or solution may be in-order.</p>
<br>
    <h3>6. CLEAN AROUND THEIR EYES TO REMOVE EYE GOOP</h3>
    <p>Some dogs are prone to accumulating excessive eye “goop”. Yeah, I know… kind-of gross. Excessing tearing or discharge collects in the corners of the eyes and can get crusty. My last dog was terribly prone to eye goop and I would carefully use a flea comb to remove it. I recommend loosening the goop with a warm wash cloth first, and then using the flea comb to remove it. Light colored dogs may have the accompanying red stain that comes with excess tearing to which you can use a dog Tear Stain removal from your local pet supply store. Keep an eye on this area. Excess discharge can be a symptom of a more serious conjunctivitis. If you see signs of irritation, redness, or a funky smell, we recommend having your vet take a look at it.</p>
<br>
    <h3>7. GIVE THEM A BATH TO KEEP THEM SMELLING GREAT</h3>
    <p>If your pup looks great, but she doesn’t smell all that great, there are a number of doggie towelettes and dry shampoos on the market. Some even contain moisturizers and conditioners to further enhance the health and appearance of your dog’s coat. I use doggie towelettes whenever my dog comes in from outside. It removes outside allergens, dirt, and pee and poop residue. By using these daily, Rex never has an odor. You may find these to be very helpful in-between Grooming appointments.</p>
{% endblock %}

gadgets/templates/gadgets/dog_selfwash.html
{% extends 'gadgets/base.html' %}
{% block title %}Dog SelfWash{% endblock %}
{% block body %}
    <h1 style="text-align: center">Dog SelfWash Tips</h1>
    <h3>Dress for the fun  :</h3>  we're washing dogs here and it's actually hard work. You may get wet and there will be some dog hair blowing.  We do provide aprons,  face masks, eye protection, and ear plugs for anyone that requests them.  If your pet is skittish, nervous around other pets, or if you are sensitive to pet hair or noise - please see our Best Self-Wash Times below for an improved experience.



<h3>Best Self-Wash Times :</h3> weekdays and afternoons (after 1:30) usually provide the best availability of our wash tubs and the least amount of distractions (dryer noise, pet hair, etc...).  Our morning hours, Fridays, Saturdays,  & Sundays are our busiest times. Although we may have very limited tub availability during these times, an appointment is required.  We recommend calling ahead and/or allowing yourself (& us) time to prepare your tub.  Please note : there are times when all tubs are being used and there are no available appointments.  Last self-wash is 1 hour before closing to allow you enough time to wash and dry your pet.

​

<h3>If you have questions, we are here to help : </h3>any available associate can assist you if you have questions about the wash or dry process.  If you notice your pet has fleas or ticks, let us know immediately and we can offer a different shampoo based on their condition.  We have shampoos for sensitive skins,  white coats,  pets that are shedding,  and even a special shampoo if your pet got "skunked".   Need advice on how to clean your pets ears, trim their nails, or anything else - just ask, we are here to help.
{% endblock %}

gadgets/templates/gadgets/dog_sitting.html
{% extends 'gadgets/base.html' %}
{% block title %}Dog Sitting{% endblock %}
{% block body %}
    <h1 style="text-align: center">Dog Sitting Tips</h1>
    <h3>1. Know Your Limitations</h3>
Many people who attempt to run an impromptu pet sitting business, or who just make themselves available for occasional pet sitting to their friends (like me), don’t really think about all the ways that pet sitting can throw you for a loop. It’s important to sit down and think about what you are comfortable doing, and what you aren’t. For example, are you capable of lifting a dog that weighs over 50 pounds? While you may not ever need to when you pet sit, you also don’t know what could happen. You may need to limit yourself to pets under 50 pounds, or whatever the case may be, to suit your physical abilities in the event of an emergency.

Also consider what kinds of pets you’ll be willing to watch – again, based on what you know you can do. Can you give a dog a medication? Probably, especially if the owner allows you to use a pill pocket. But what about a bird? Are you willing to feed a pet snake?


<h3>2. Do Your Research</h3>
Ideally, you’ll have plenty of time to ask questions about the pet before you are due to show up for the pet sitting job. When you are asked to pet sit, be sure that you do some research about the pet. Ask about all the usual things, of course, such as their feeding schedule, any medications, their exercise needs, and so on. But also ask if there’s anything that scares the dog, if there’s someone (like the mailman) that they hate, if they have a tendency to bolt towards an open door, if they have any allergies, what their favorite games are, and so on. The more you know about the dog, the easier your job will be. You may also want to do some basic research into the breed to get an idea of what level of exercise they may need.

<h3>3. Consider Financial Obligations</h3>
When you are caring for a live creature, there are always financial obligations that may arise. For example, the dog may get injured and need veterinary care; the owners may have forgotten to top off the food before they left, and now the dog has run out. In any case like this, it’s important to know ahead of time how the bill will be handled. Will they leave an emergency stash of cash, or will they reimburse you for any purchases? Will their vet bill them for any services needed? Be sure that you know what vet they use for both regular working hours and emergency hours.

<h3>4. Stick to a Routine</h3>
Not every pet that you meet will warm up to you, and that’s okay. Remember that the pet is confused about where his owner went and is likely mourning what he sees as a loss till his owner returns. One of the best things you can do for a dog in this situation is to keep them on a routine. If you can stick to their usual routine with their owner – such as a walk in the morning, breakfast, and then another walk after dinner in the evening – this will help them make sense out of their situation. If you can’t stick to their usual schedule, then stay as close as you can, and be sure that the schedule you are using stays the same on all the days that you are pet sitting. The dog will feel much more grounded and calm if they know what to expect, and the owners will come back to a dog that hasn’t gone totally crazy in their absence.

<h3>5. Be Very Confident with a Leash</h3>
If there’s anything that you must be confident with as a pet sitter, it’s using a leash. You need to be able to control any dog, even a dog that is anxious or skittish, with a leash. Many dog sitters will attempt to walk dogs from multiple households at once, but unless these dogs know each other, it’s a bad idea to introduce them without their owners present. Having a heavy duty leash that you are familiar with is more important than using the dog’s own leash. You may want to keep a few backup leashes in your car that you know you can trust. One heavy-duty leash I really like is the police dog training leash by Pettom. It has elastic to absorb shock if a dog pulls, and is made to withstand a lot of force.

<h3>6. Stay in Touch</h3>
Perhaps one of the reasons that my friends like me pet sitting for them is that I’m not above snapping a bunch of pictures of their dogs and sending them a quick text. Dog lovers like to know that their furry pal is safe and happy while they are traveling. If you can, email, text, or otherwise contact the dog owner on a regular basis while they are gone. One fun way to do this may be to send them a picture or an update on social media, which they may be more willing to check than their email while on vacation. This also ensures that you can get quick advice should any emergencies arise while they are away. Don’t interrupt their hard-earned vacation, of course, but do have a way to get in contact with them.

<h3>7. Know the Household</h3>
Many pet sitters often end up being house sitters as well. Even if you aren’t staying in the house, the dog may be staying their overnight while you take care of them two or three times a day. If you have to be in or go to their house at all, be sure that you know the ins and outs of their household. Do they have other help that will be showing up (cleaning lady, gardener, etc.)? Are they expecting any handymen or servicemen to come by while they are gone? Do any of their friends or relatives have keys to the house, and would any of them show up during your time there? It’s important for both your safety and the safety of the house, that you know who is and isn’t okay to be on the property.

<h3>8. Follow Basic Safety Rules</h3>
To keep yourself safe while pet sitting, you should follow some basic safety rules. Don’t walk the dog after dark if you are in an unfamiliar area. Don’t approach the dog while she is eating, even if she has been very friendly with you so far. Be careful when picking up a dog, unless you know for sure that she’s comfortable with that. If you are playing with the dog, it may be safer to choose a toy that gives you some space between your body and theirs, such as a flirt pole or a tug of war rope. If you pet sit often or run a business as a pet sitter, getting some kind of insurance is a very good idea. Even the sweetest dogs can have unpredictable reactions in new situations. Insurance also shows clients that you are a responsible business owner, which can help you get more business in the future.

<h3>9. Stay Organized</h3>
Even if you are only sitting one pet at a time, it’s still important that you are a very organized person. You’ll need to keep all the pet’s routines, special needs, and contact information in a safe and accessible place. You’ll also need to be able to find their toys, bed, food, and everything else at a moment’s notice. If you are sitting multiple pets at once, visiting each house every day, then you’ll need to be even more organized so that each pet gets the proper care. It’s vital that you stick to your routines because that helps the pets feel more stable – and to do that, you need to be as organized as you can be. This will ensure that no pet is accidentally fed at the wrong time, giving medication at the wrong dose, or not given the care that they needed because you confused them with another dog.

<h3>10. Be Calm</h3>
Dogs that are anxious pick up on a lot of the behaviors of those around them. If you are not a calm person who can handle any emergency thrown your way with grace and patience, then you may not be the best pet sitter in the world. Pets need a person to be very calm during this time because they will already be worked up over losing their owner for however brief a time. Make sure that you remain calm will help them deal with their own anxiety better, and it also helps you stay level-headed during emergencies. If you are the type of person who gets anxious when emergencies arise, consider that pet sitting may not be the best option for you. Having a very detailed emergency plan regarding vet care, unexpected costs, runaways, illnesses, and any other contingency can help.

<h3>11. Pay Attention to Pet Body Language</h3>
The most important thing you can do as a pet sitter is to be sensitive to the way pets communicate. Pay attention to their body language and behavior while you are with them. It may be that a dog needs to be given some space to process what’s going on, or it may be that distracting a dog with a fun game could help them stop pacing around. You’ll have to gain experience in understanding how to read dogs’ body language and behaviors, and the sooner you can develop this skill, the better. Be sure that you have a good handle on positive training techniques so that you understand how best to connect with a dog, even for the short amount of time that you’ll be there.
{% endblock %}

gadgets/templates/gadgets/dog_training.html
{% extends 'gadgets/base.html' %}
{% block title %}Dog Training{% endblock %}
{% block body %}

    <h1 style="text-align: center">Dog Training Tips</h1>
    <br><br>
    <h3>1. Listen to Your Dog</h3>
    <p>Learn to listen to your dog. If your dog appears to be uncomfortable meeting another dog, animal or person, don’t insist that he say hello. He’s telling you that he isn’t comfortable
        for a reason, and you should respect that. Forcing the issue can often result in bigger problems down the line.</p>
    <br>
    <h3>2. Be Generous with Your Affection</h3>
    <p>Most people don’t have a problem being very clear about when they are unhappy with their dogs, but, they often ignore the good stuff. Big mistake!
        Make sure you give your dog lots of attention when he’s doing the right thing. Let him know when he’s been a good boy.
        That’s the time to be extra generous with your attention and praise. It’s even okay to be a little over the top.</p>
    <br>
    <h3>3. Does He Really Like It?</h3>
    <p>Just because the bag says “a treat all dogs love” doesn’t mean your dog will automatically love it. Some dogs are very selective about what they like to eat. Soft and
        chewy treats are usually more exciting for your dog than hard and crunchy treats. Keep your eyes open for what he enjoys.</p>
    <br>
    <h3>4. Tell Him What You Want Him to Do</h3>
    <p>There is nothing inherently wrong with telling your dog “no,” except that it doesn’t give him enough information. Instead of telling your dog “no,” tell him what you want him to do. Dogs don’t generalize well, so if your dog jumps up on someone to say
        hello and you say no, he may jump higher or he may jump to the left side instead of the right. A better alternative would be to ask him to “sit.” Tell him what you want him to do in order to avoid confusion.</p>
    <br>
    <h3>5. Be Consistent</h3>
    <p>Whenever you’re training your dog, it’s important to get as many family members involved as possible so everyone’s on the same
        page. If you are telling your dog “off” when he jumps on the couch and someone else is saying “down,” while someone
        else is letting him hang out up there, how on earth is he ever going to learn what you want? Consistency will be
        the key to your success.</p>
    <br>
    <h3>6. Have Realistic Expectations</h3>
    <p>Changing behavior takes time. You need to have realistic expectations about changing your dog’s behavior as well as
        how long it will take to change behaviors that you don’t like. Often behaviors which are “normal” doggie behaviors
        will take the most time such as barking, digging and jumping. You also need to consider how long your dog has
        rehearsed the behavior. For example, if you didn’t mind that your dog jumped up on people to say hi for the
        last seven years and now you decide that you don’t want him to do that anymore, that behavior will take a much
        longer time to undo than if you had addressed it when he was a pup. Remember it’s never too late to change the
        behavior some will just take longer than others.</p>
    <br>
    <h3>7. Don’t Underestimate the Benefits of Feeding a High Quality Food</h3>
    <p>Feed your dog a high-quality diet with appropriate amounts of protein. If your dog spends most of his days lounging
        in your condo, don’t feed him food with a protein level that is ideal for dogs who herd sheep all day. The money
        that you will spend on feeding an appropriate quality food will often be money that you save in vet bills later on.
        I recommend you always check with your veterinarian for the right diet for your dog.</p>
    <br>
    <h3>8. You Get What You Reinforce – Not Necessarily What You Want</h3>
    <p>If your dog exhibits a behavior you don’t like, there is a strong likelihood that it’s something that has been reinforced before. A great example is when your dog brings you a toy and barks to entice you to throw it. You throw the toy. Your dog has just learned that barking gets you to do what he wants. You say “no,” and he barks even more. Heaven forbid you give in and throw the toy now! Why? Because you will have taught him persistence pays off. Before you know it you’ll have a dog that barks and barks every time he wants something.
        The solution? Ignore his barking or ask him to do something for you (like “sit”) before you throw his toy.</p>
    <br>
    <h3>9. Bribery vs. Reward</h3>
    <p>The idea of using treats to train is often equated with bribery. Truthfully, dogs do what works.
        If using treats gets them to do what you want, then why not? You can also use the world around you as a
        reinforcement. Every interaction you have with your dog is a learning opportunity, so when you think about it,
        you probably don’t use food very often except during active training sessions. So why does your dog continue to
        hang out? Because you reinforce him with praise, touch, games and walks. Just remember, the behavior should produce
        the treat; the treat should not produce the behavior.</p>
    <br>
    <h3>10. Freedom</h3>
    <p>Let your new dog gradually earn freedom throughout your home. A common error that many pet parents make is giving
        their new dog too much freedom too soon. This can easily lead to accidents relating to housetraining and
        destructive chewing. So, close off doors to unoccupied rooms and use baby gates to section off parts of the
        house, if necessary. One of the best ways to minimize incidents is to keep your dog tethered to you in the
        house and by using a crate or doggie safe area when you can’t actively supervise him.</p>

{% endblock %}

gadgets/templates/gadgets/experts.html
{% extends 'gadgets/base.html' %}
{% block title %}Our Experts{% endblock %}
{% block body %}
    <h2>Thank You for contact. Our Experts will call you soon...</h2>
{% endblock %}

gadgets/templates/gadgets/login.html
{% extends 'gadgets/base.html' %}
{% block title %}Login{% endblock %}

{% block body %}
    <div class="container">
    <div class="container">
    <div class="col-sm-6">
    <div class="panel panel-primary">
    <div class="panel-heading"><h2 style="text-align: center">Login</h2></div>
    <div class="panel-body">

    <form class="form-horizontal" method="post" enctype="multipart/form-data">
    <center>
    {% csrf_token%}
    {% for field in form %}
        <span class="danger">{{ field.errors }}</span><br><br>
        <label>{{ field.label_tag }}</label>
        {{ field }}
    {% endfor %}</center>
    <br><br>
    <button type="submit" class="btn btn-primary" value="SignIn" style="margin-left: 70%;margin-top: -10px">submit</button><br><br>
    </form>
    <script>
    {% if messages %}
                {% for message in messages %}
                    alert(message);
                {% endfor %}
            {% endif %}
    </script>
    </div>
    </div>
    </div>
    </div>
</div>
{% endblock %}

gadgets/templates/gadgets/summary.html
{% extends 'gadgets/base.html' %}

{% block title %}{{ cat.category }}{% endblock %}
{% block body %}
<div class="row">
{% for prod in cat.product_set.all %}
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="{{ prod.image.url }}" alt="...">
      <div class="caption">
        <h3>{{ prod.ptitle}}</h3>
          <h4>{{ prod.brand}}</h4>
          <p>Price : <srtike>{{ prod.price }}</srtike><br>Actual price : {{ prod.act_price }}</p>



      </div>
    </div>
  </div>
{% endfor %}
</div>
{% endblock %}